export const SECTION_MOTION_TOKENS = {
  timing: {
    ease: 'easeOut' as const,
    lineDuration: 0.7,
    contentDuration: 0.5,
    quickDuration: 0.3,
    headerDuration: 0.45,
    drawDuration: 0.7,
    riseOffset: 14,
    panelOffset: 12,
    panelExitOffset: -8,
    headerOffset: -12,
  },
  revealLine: {
    duration: 0.7,
    ease: 'easeOut' as const,
    viewportAmount: 0.3,
  },
  hero: {
    headingDuration: 0.5,
    headingDelay: 0.08,
    bodyDuration: 0.5,
    bodyDelay: 0.14,
    ctaDuration: 0.5,
    ctaDelay: 0.2,
    riseOffset: 14,
  },
  sectionGrid: {
    viewportAmount: 0.2,
    once: true,
    staggerChildren: 0.1,
    delayChildren: 0.04,
  },
  embedded: {
    itemDuration: 0.5,
  },
  dashboard: {
    pollIntervalMs: 5000,
    statusFadeDuration: 0.45,
    statusRiseOffset: 14,
    staggerChildren: 0.09,
    delayChildren: 0.03,
    itemDuration: 0.5,
  },
  muel: {
    revealOnce: false,
    viewportAmount: 0.34,
    viewportMargin: '0px 0px -4% 0px',
    uiEase: 'cubic-bezier(0.22, 1, 0.36, 1)',
    revealDurationMs: 600,
    revealOffsetPx: 20,
    componentDuration: 0.2,
    componentDelayStep: 0.02,
    componentOpacity: 0.9,
    componentY: 8,
    componentScale: 0.997,
    componentBlurPx: 0,
    featureDuration: 0.2,
    featureDelayStep: 0.02,
    featureY: 10,
    featureX: 8,
    featureScale: 0.997,
    metricCountDurationMs: 560,
    metricCountEasePower: 0.86,
    hoverLiftPx: 2,
    hoverScale: 1.01,
    activeScale: 0.996,
    hoverDurationMs: 160,
    cardTransitionMs: 220,
    linkTransitionMs: 200,
    menuTransitionMs: 180,
    underlineTransitionMs: 170,
    microUnderlineTransitionMs: 340,
    mediaZoomDurationMs: 420,
    skipLinkTransitionMs: 180,
    glitchDurationAMs: 2200,
    glitchDurationBMs: 2600,
    dockEnterDurationMs: 240,
    visualCardShadowYRestPx: 8,
    visualCardShadowBlurRestPx: 26,
    visualCardShadowYHoverPx: 12,
    visualCardShadowBlurHoverPx: 32,
    visualCardShadowTintRestPct: 8,
    visualCardShadowTintHoverPct: 20,
    visualCardOverlayAccentPct: 22,
    visualCardOverlayOpacityRest: 0.38,
    visualCardOverlayOpacityHover: 0.55,
    visualChartInsetAccentPct: 12,
    visualRadarCorePulseDurationMs: 1800,
    visualRadarCorePulseMinOpacity: 0.64,
    visualRadarCorePulseMaxOpacity: 1,
    visualRadarCorePulseScale: 1.18,
  },
} as const;

export const HUB_VIEW_TOKENS = {
  defaultItemsGrid: 'grid grid-cols-1 overflow-hidden rounded-xl border-l border-t border-zinc-800 md:grid-cols-3',
  compactItemsGrid: 'grid grid-cols-1 overflow-hidden rounded-xl border-l border-t border-zinc-800 md:grid-cols-2',
} as const;
